// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Hw8gVc5Y22tB_cMZYP32Evd9_ftq8k4',
    appId: '1:16388535273:web:4d9001d7e1f6641e38d178',
    messagingSenderId: '16388535273',
    projectId: 'nibbl-b8d73',
    authDomain: 'nibbl-b8d73.firebaseapp.com',
    databaseURL: 'https://nibbl-b8d73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nibbl-b8d73.appspot.com',
    measurementId: 'G-LD9KYBZG16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5mAEdXi5xc1anND5E70W-Qz2oAjaJS4',
    appId: '1:16388535273:android:49aacf67b2a2e19938d178',
    messagingSenderId: '16388535273',
    projectId: 'nibbl-b8d73',
    databaseURL: 'https://nibbl-b8d73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nibbl-b8d73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa4p6GCchb8PdVRQmpwcqDzh3Tg8Z-h7Q',
    appId: '1:16388535273:ios:9a20a016d0fce4b538d178',
    messagingSenderId: '16388535273',
    projectId: 'nibbl-b8d73',
    databaseURL: 'https://nibbl-b8d73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nibbl-b8d73.appspot.com',
    androidClientId: '16388535273-4u7tast44m1o6fsd9jcir1pbrfr9k2po.apps.googleusercontent.com',
    iosClientId: '16388535273-ionfe2ikbktf14cqpdh2auu6f1bttq76.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa4p6GCchb8PdVRQmpwcqDzh3Tg8Z-h7Q',
    appId: '1:16388535273:ios:9a20a016d0fce4b538d178',
    messagingSenderId: '16388535273',
    projectId: 'nibbl-b8d73',
    databaseURL: 'https://nibbl-b8d73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nibbl-b8d73.appspot.com',
    androidClientId: '16388535273-4u7tast44m1o6fsd9jcir1pbrfr9k2po.apps.googleusercontent.com',
    iosClientId: '16388535273-ionfe2ikbktf14cqpdh2auu6f1bttq76.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD0eS9QbylfFGDh8LAbiHhJbff99KOkDc',
    appId: '1:16388535273:web:541c3cf056e7be2e38d178',
    messagingSenderId: '16388535273',
    projectId: 'nibbl-b8d73',
    authDomain: 'nibbl-b8d73.firebaseapp.com',
    databaseURL: 'https://nibbl-b8d73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nibbl-b8d73.appspot.com',
    measurementId: 'G-YVT0PVWRT4',
  );
}
